name: EasyI18n CI

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
        
    - name: Setup net6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies EasyI18n
      run: dotnet restore EasyI18n\EasyI18N.sln      
      
    - name: Build
      run: dotnet build EasyI18n\EasyI18N.sln --configuration Release --no-restore 
      
    - name: Test
      run: dotnet test EasyI18n\EasyI18N.sln --configuration Release  --no-build --verbosity normal
