name: Publish EasyI18n nuget packages

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: Dump dir content      
      run: |
          dir
          dir EasyI18n
          echo "Workspace root -> $GITHUB_WORKSPACE"
        
    - name: Setup net6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies EasyI18n
      run: dotnet restore $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln      
      
    - name: Build
      run: dotnet build $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln --configuration Release --no-restore 
      
    - name: Test
      run: dotnet test $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln --configuration Release  --no-build --verbosity normal

    - name: Create nuget package
      run: dotnet pack $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln --configuration Release

    - name: Publish nuget package
      run: dotnet nuget push "$GITHUB_WORKSPACE/EasyI18n/bin/Release/*.nupkg"  --api-key ${{secrets.NUGET_PAT}} --source "github" --skip-duplicate --no-symbols true
