name: Publish EasyI18n nuget packages

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: Dump dir content      
      run: |
          dir
          dir EasyI18n
          echo "Workspace root -> $GITHUB_WORKSPACE"
        
    - name: Setup net6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies EasyI18n
      run: dotnet restore $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln      
      
    - name: Build
      run: dotnet build $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln --configuration Release --no-restore 
      
    - name: Test
      run: dotnet test $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln --configuration Release  --no-build --verbosity normal

    - name: Create nuget package EasyI18n
      run: dotnet pack $GITHUB_WORKSPACE/EasyI18n/EasyI18N.sln --configuration Release

    - name: Add nuget source
      run: dotnet nuget add source --username Sigurdur42 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"

    - name: Publish nuget package EasyI18n
      continue-on-error: true
      run: dotnet nuget push "$GITHUB_WORKSPACE/EasyI18n/EasyI18n/bin/Release/*.nupkg" --source "github" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_PAT}} 

    - name: Publish nuget package EasyI18n.Generator
      continue-on-error: true
      run: dotnet nuget push "$GITHUB_WORKSPACE/EasyI18n/EasyI18N.Generator/bin/Release/*.nupkg" --source "github" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_PAT}} 
